### ISSUE TITLE
How to deal with nightly-only tools?

### ISSUE THREAD

**Issue by pravic** [nabijaczleweli/cargo-update#88] opened 2018-07-26 04:40 UTC
E.g. [cargo-modules](https://github.com/regexident/cargo-modules).

I would not want to install all cargo tools with nightly, but some of them are required to be compiled by nightly. May be, it would be nice to track them via some config (published online or maintained by user himself).

**Comment by nabijaczleweli** [comment] 2018-07-26 16:36
In what way does [`cargo install-update-config`](https://cdn.rawgit.com/nabijaczleweli/cargo-update/man/cargo-install-update-config.1.html) not satisfy that (I might just not be seeing it)?

**Comment by nabijaczleweli** [comment] 2018-07-26 16:38
(Semi-dupe of #25)

**Comment by pravic** [comment] 2018-07-26 16:58
Didn't know about that! Thanks, I'll try it.

**Comment by nabijaczleweli** [comment] 2018-07-26 21:30
Do please report back with how that went

**Comment by pravic** [comment] 2018-08-19 04:01
Well, I've been waiting for a nightly module update and here we are:

> $ cargo install-update-config -t nightly cargo-modules
> $ cargo install-update -a
Updated 1 package.

Works like a charm. Thanks!

**Comment by nabijaczleweli** [comment] 2018-08-19 15:05
Nothing quite like an another satisfied customer!

**Closed by nabijaczleweli** 2018-08-19 15:05 UTC
Labels: question
