### ISSUE TITLE
name conflict `cargo-update`

### ISSUE THREAD

**Issue by LucianoBestia** [nabijaczleweli/cargo-update#133] opened 2020-05-27 08:13 UTC
In the Cargo Book there is also a command with the same name:
https://doc.rust-lang.org/cargo/commands/cargo-update.html

But it does another thing:
`cargo-update - Update dependencies as recorded in the local lock file`
and not
`A cargo subcommand for checking and applying updates to installed executables`

This is a confusing name conflict. 
In neither of this 2 names is clear what is actually being updated?
"Cargo" is not being updated by any of these, to be clear.
One could be `update_ installed_executables`
The other `update_cargo_toml_dependencies`

**Comment by nabijaczleweli** [comment] 2020-05-27 13:02
The `src:cargo-update` package produces two binaries: `cargo-install-update` and `cargo-install-update-config`. This is clearly outlined in the package description, README and both manpages.

Closing as duplicate of #101

**Closed** 2020-05-27 13:03 UTC
Labels: duplicate
