### ISSUE TITLE
Is there a way to list only packages in need of update?

### ISSUE THREAD

**Issue by jbr** [nabijaczleweli/cargo-update#259] opened 2024-05-21 18:07 UTC
Currently I use this ungainly nushell snippet to filter only the "Needs Update: Yes" columns: `cargo install-update --list | tail -n+3 | from ssv | where "Needs update" =~ "Yes"`. Is there a way to do this with just arguments to `cargo install-update`? If not, would you be interested in a PR for `cargo install-update --list --updates` or `cargo install-update --list-updates`

**Comment by nabijaczleweli** [comment] 2024-05-21 18:16
`| grep Yes$` is the stable interface for this.

Dupe of #175 I think.

**Closed by nabijaczleweli** 2024-05-21 18:16 UTC
