### ISSUE TITLE
install-update not found after installing cargo-update

### ISSUE THREAD

**Issue by pitdicker** [nabijaczleweli/cargo-update#70] opened 2018-03-21 06:53 UTC
In `rand` we have the CI failing but no idea why. We use `cargo-install` to install `cargo-web`. Now, after installing `cargo-install`, we get this error:
```
$ cargo install-update -i cargo-web
error: The subcommand 'install-update' wasn't recognized
	Did you mean 'install'?
```
See https://github.com/rust-lang-nursery/rand/pull/316, and https://travis-ci.org/rust-lang-nursery/rand/jobs/355808430 for the latest log.

Do you have some idea?

**Comment by mati865** [comment] 2018-03-21 07:18
Duplicate of https://github.com/nabijaczleweli/cargo-update/issues/68

**Comment by nabijaczleweli** [comment] 2018-03-21 20:15
Closing as dupe of #68. (Thanks @mati865)

**Closed by nabijaczleweli** 2018-03-21 20:15 UTC
Labels: duplicate
