### ISSUE TITLE
Add Cargo.lock to repository

### ISSUE THREAD

**Issue by ishitatsuyuki** [nabijaczleweli/cargo-update#30] opened 2017-05-15 03:34 UTC
Cargo.lock is normally included for projects with a binary. By the way, it's ignored when building as library dependency.

**Comment by nabijaczleweli** [comment] 2017-05-15 09:45
Dupe of #10

**Comment by ishitatsuyuki** [comment] 2017-05-15 09:47
May I continue the discussion here? All projects contains more than one binary, independent of the usecase, **should** have a lockfile. 

http://doc.crates.io/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by nabijaczleweli** [comment] 2017-05-15 10:30
No, you mayn't. The executable is a usage example. EOT

**Closed** 2017-05-15 10:30 UTC
Labels: duplicate, invalid
